spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
      interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: local-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.learning.department_service.model"
        interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor

logging:
  level:
    org.springframework.kafka: DEBUG