/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.telemetry.info.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CabLocationSpeed extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7386772910648652971L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CabLocationSpeed\",\"namespace\":\"com.telemetry.info.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"timestamp\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"location\",\"type\":{\"type\":\"record\",\"name\":\"Location\",\"fields\":[{\"name\":\"lat\",\"type\":\"double\"},{\"name\":\"lon\",\"type\":\"double\"}]}},{\"name\":\"bearing\",\"type\":\"double\"},{\"name\":\"milesPerHour\",\"type\":\"double\"},{\"name\":\"h3\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"geohash\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CabLocationSpeed> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CabLocationSpeed> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CabLocationSpeed> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CabLocationSpeed> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CabLocationSpeed> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CabLocationSpeed to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CabLocationSpeed from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CabLocationSpeed instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CabLocationSpeed fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int id;
  private long timestamp;
  private com.telemetry.info.avro.Location location;
  private double bearing;
  private double milesPerHour;
  private java.lang.CharSequence h3;
  private java.lang.CharSequence geohash;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CabLocationSpeed() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param timestamp The new value for timestamp
   * @param location The new value for location
   * @param bearing The new value for bearing
   * @param milesPerHour The new value for milesPerHour
   * @param h3 The new value for h3
   * @param geohash The new value for geohash
   */
  public CabLocationSpeed(java.lang.Integer id, java.lang.Long timestamp, com.telemetry.info.avro.Location location, java.lang.Double bearing, java.lang.Double milesPerHour, java.lang.CharSequence h3, java.lang.CharSequence geohash) {
    this.id = id;
    this.timestamp = timestamp;
    this.location = location;
    this.bearing = bearing;
    this.milesPerHour = milesPerHour;
    this.h3 = h3;
    this.geohash = geohash;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return timestamp;
    case 2: return location;
    case 3: return bearing;
    case 4: return milesPerHour;
    case 5: return h3;
    case 6: return geohash;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: location = (com.telemetry.info.avro.Location)value$; break;
    case 3: bearing = (java.lang.Double)value$; break;
    case 4: milesPerHour = (java.lang.Double)value$; break;
    case 5: h3 = (java.lang.CharSequence)value$; break;
    case 6: geohash = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public int getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'location' field.
   * @return The value of the 'location' field.
   */
  public com.telemetry.info.avro.Location getLocation() {
    return location;
  }


  /**
   * Sets the value of the 'location' field.
   * @param value the value to set.
   */
  public void setLocation(com.telemetry.info.avro.Location value) {
    this.location = value;
  }

  /**
   * Gets the value of the 'bearing' field.
   * @return The value of the 'bearing' field.
   */
  public double getBearing() {
    return bearing;
  }


  /**
   * Sets the value of the 'bearing' field.
   * @param value the value to set.
   */
  public void setBearing(double value) {
    this.bearing = value;
  }

  /**
   * Gets the value of the 'milesPerHour' field.
   * @return The value of the 'milesPerHour' field.
   */
  public double getMilesPerHour() {
    return milesPerHour;
  }


  /**
   * Sets the value of the 'milesPerHour' field.
   * @param value the value to set.
   */
  public void setMilesPerHour(double value) {
    this.milesPerHour = value;
  }

  /**
   * Gets the value of the 'h3' field.
   * @return The value of the 'h3' field.
   */
  public java.lang.CharSequence getH3() {
    return h3;
  }


  /**
   * Sets the value of the 'h3' field.
   * @param value the value to set.
   */
  public void setH3(java.lang.CharSequence value) {
    this.h3 = value;
  }

  /**
   * Gets the value of the 'geohash' field.
   * @return The value of the 'geohash' field.
   */
  public java.lang.CharSequence getGeohash() {
    return geohash;
  }


  /**
   * Sets the value of the 'geohash' field.
   * @param value the value to set.
   */
  public void setGeohash(java.lang.CharSequence value) {
    this.geohash = value;
  }

  /**
   * Creates a new CabLocationSpeed RecordBuilder.
   * @return A new CabLocationSpeed RecordBuilder
   */
  public static com.telemetry.info.avro.CabLocationSpeed.Builder newBuilder() {
    return new com.telemetry.info.avro.CabLocationSpeed.Builder();
  }

  /**
   * Creates a new CabLocationSpeed RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CabLocationSpeed RecordBuilder
   */
  public static com.telemetry.info.avro.CabLocationSpeed.Builder newBuilder(com.telemetry.info.avro.CabLocationSpeed.Builder other) {
    if (other == null) {
      return new com.telemetry.info.avro.CabLocationSpeed.Builder();
    } else {
      return new com.telemetry.info.avro.CabLocationSpeed.Builder(other);
    }
  }

  /**
   * Creates a new CabLocationSpeed RecordBuilder by copying an existing CabLocationSpeed instance.
   * @param other The existing instance to copy.
   * @return A new CabLocationSpeed RecordBuilder
   */
  public static com.telemetry.info.avro.CabLocationSpeed.Builder newBuilder(com.telemetry.info.avro.CabLocationSpeed other) {
    if (other == null) {
      return new com.telemetry.info.avro.CabLocationSpeed.Builder();
    } else {
      return new com.telemetry.info.avro.CabLocationSpeed.Builder(other);
    }
  }

  /**
   * RecordBuilder for CabLocationSpeed instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CabLocationSpeed>
    implements org.apache.avro.data.RecordBuilder<CabLocationSpeed> {

    private int id;
    private long timestamp;
    private com.telemetry.info.avro.Location location;
    private com.telemetry.info.avro.Location.Builder locationBuilder;
    private double bearing;
    private double milesPerHour;
    private java.lang.CharSequence h3;
    private java.lang.CharSequence geohash;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.telemetry.info.avro.CabLocationSpeed.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.location)) {
        this.location = data().deepCopy(fields()[2].schema(), other.location);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasLocationBuilder()) {
        this.locationBuilder = com.telemetry.info.avro.Location.newBuilder(other.getLocationBuilder());
      }
      if (isValidValue(fields()[3], other.bearing)) {
        this.bearing = data().deepCopy(fields()[3].schema(), other.bearing);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.milesPerHour)) {
        this.milesPerHour = data().deepCopy(fields()[4].schema(), other.milesPerHour);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.h3)) {
        this.h3 = data().deepCopy(fields()[5].schema(), other.h3);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.geohash)) {
        this.geohash = data().deepCopy(fields()[6].schema(), other.geohash);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing CabLocationSpeed instance
     * @param other The existing instance to copy.
     */
    private Builder(com.telemetry.info.avro.CabLocationSpeed other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.location)) {
        this.location = data().deepCopy(fields()[2].schema(), other.location);
        fieldSetFlags()[2] = true;
      }
      this.locationBuilder = null;
      if (isValidValue(fields()[3], other.bearing)) {
        this.bearing = data().deepCopy(fields()[3].schema(), other.bearing);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.milesPerHour)) {
        this.milesPerHour = data().deepCopy(fields()[4].schema(), other.milesPerHour);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.h3)) {
        this.h3 = data().deepCopy(fields()[5].schema(), other.h3);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.geohash)) {
        this.geohash = data().deepCopy(fields()[6].schema(), other.geohash);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public int getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.telemetry.info.avro.CabLocationSpeed.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.telemetry.info.avro.CabLocationSpeed.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.telemetry.info.avro.CabLocationSpeed.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.telemetry.info.avro.CabLocationSpeed.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'location' field.
      * @return The value.
      */
    public com.telemetry.info.avro.Location getLocation() {
      return location;
    }


    /**
      * Sets the value of the 'location' field.
      * @param value The value of 'location'.
      * @return This builder.
      */
    public com.telemetry.info.avro.CabLocationSpeed.Builder setLocation(com.telemetry.info.avro.Location value) {
      validate(fields()[2], value);
      this.locationBuilder = null;
      this.location = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'location' field has been set.
      * @return True if the 'location' field has been set, false otherwise.
      */
    public boolean hasLocation() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'location' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.telemetry.info.avro.Location.Builder getLocationBuilder() {
      if (locationBuilder == null) {
        if (hasLocation()) {
          setLocationBuilder(com.telemetry.info.avro.Location.newBuilder(location));
        } else {
          setLocationBuilder(com.telemetry.info.avro.Location.newBuilder());
        }
      }
      return locationBuilder;
    }

    /**
     * Sets the Builder instance for the 'location' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.telemetry.info.avro.CabLocationSpeed.Builder setLocationBuilder(com.telemetry.info.avro.Location.Builder value) {
      clearLocation();
      locationBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'location' field has an active Builder instance
     * @return True if the 'location' field has an active Builder instance
     */
    public boolean hasLocationBuilder() {
      return locationBuilder != null;
    }

    /**
      * Clears the value of the 'location' field.
      * @return This builder.
      */
    public com.telemetry.info.avro.CabLocationSpeed.Builder clearLocation() {
      location = null;
      locationBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'bearing' field.
      * @return The value.
      */
    public double getBearing() {
      return bearing;
    }


    /**
      * Sets the value of the 'bearing' field.
      * @param value The value of 'bearing'.
      * @return This builder.
      */
    public com.telemetry.info.avro.CabLocationSpeed.Builder setBearing(double value) {
      validate(fields()[3], value);
      this.bearing = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'bearing' field has been set.
      * @return True if the 'bearing' field has been set, false otherwise.
      */
    public boolean hasBearing() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'bearing' field.
      * @return This builder.
      */
    public com.telemetry.info.avro.CabLocationSpeed.Builder clearBearing() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'milesPerHour' field.
      * @return The value.
      */
    public double getMilesPerHour() {
      return milesPerHour;
    }


    /**
      * Sets the value of the 'milesPerHour' field.
      * @param value The value of 'milesPerHour'.
      * @return This builder.
      */
    public com.telemetry.info.avro.CabLocationSpeed.Builder setMilesPerHour(double value) {
      validate(fields()[4], value);
      this.milesPerHour = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'milesPerHour' field has been set.
      * @return True if the 'milesPerHour' field has been set, false otherwise.
      */
    public boolean hasMilesPerHour() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'milesPerHour' field.
      * @return This builder.
      */
    public com.telemetry.info.avro.CabLocationSpeed.Builder clearMilesPerHour() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'h3' field.
      * @return The value.
      */
    public java.lang.CharSequence getH3() {
      return h3;
    }


    /**
      * Sets the value of the 'h3' field.
      * @param value The value of 'h3'.
      * @return This builder.
      */
    public com.telemetry.info.avro.CabLocationSpeed.Builder setH3(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.h3 = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'h3' field has been set.
      * @return True if the 'h3' field has been set, false otherwise.
      */
    public boolean hasH3() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'h3' field.
      * @return This builder.
      */
    public com.telemetry.info.avro.CabLocationSpeed.Builder clearH3() {
      h3 = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'geohash' field.
      * @return The value.
      */
    public java.lang.CharSequence getGeohash() {
      return geohash;
    }


    /**
      * Sets the value of the 'geohash' field.
      * @param value The value of 'geohash'.
      * @return This builder.
      */
    public com.telemetry.info.avro.CabLocationSpeed.Builder setGeohash(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.geohash = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'geohash' field has been set.
      * @return True if the 'geohash' field has been set, false otherwise.
      */
    public boolean hasGeohash() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'geohash' field.
      * @return This builder.
      */
    public com.telemetry.info.avro.CabLocationSpeed.Builder clearGeohash() {
      geohash = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CabLocationSpeed build() {
      try {
        CabLocationSpeed record = new CabLocationSpeed();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        if (locationBuilder != null) {
          try {
            record.location = this.locationBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("location"));
            throw e;
          }
        } else {
          record.location = fieldSetFlags()[2] ? this.location : (com.telemetry.info.avro.Location) defaultValue(fields()[2]);
        }
        record.bearing = fieldSetFlags()[3] ? this.bearing : (java.lang.Double) defaultValue(fields()[3]);
        record.milesPerHour = fieldSetFlags()[4] ? this.milesPerHour : (java.lang.Double) defaultValue(fields()[4]);
        record.h3 = fieldSetFlags()[5] ? this.h3 : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.geohash = fieldSetFlags()[6] ? this.geohash : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CabLocationSpeed>
    WRITER$ = (org.apache.avro.io.DatumWriter<CabLocationSpeed>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CabLocationSpeed>
    READER$ = (org.apache.avro.io.DatumReader<CabLocationSpeed>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.id);

    out.writeLong(this.timestamp);

    this.location.customEncode(out);

    out.writeDouble(this.bearing);

    out.writeDouble(this.milesPerHour);

    if (this.h3 == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.h3);
    }

    out.writeString(this.geohash);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readInt();

      this.timestamp = in.readLong();

      if (this.location == null) {
        this.location = new com.telemetry.info.avro.Location();
      }
      this.location.customDecode(in);

      this.bearing = in.readDouble();

      this.milesPerHour = in.readDouble();

      if (in.readIndex() != 1) {
        in.readNull();
        this.h3 = null;
      } else {
        this.h3 = in.readString(this.h3 instanceof Utf8 ? (Utf8)this.h3 : null);
      }

      this.geohash = in.readString(this.geohash instanceof Utf8 ? (Utf8)this.geohash : null);

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readInt();
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          if (this.location == null) {
            this.location = new com.telemetry.info.avro.Location();
          }
          this.location.customDecode(in);
          break;

        case 3:
          this.bearing = in.readDouble();
          break;

        case 4:
          this.milesPerHour = in.readDouble();
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.h3 = null;
          } else {
            this.h3 = in.readString(this.h3 instanceof Utf8 ? (Utf8)this.h3 : null);
          }
          break;

        case 6:
          this.geohash = in.readString(this.geohash instanceof Utf8 ? (Utf8)this.geohash : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










